### PR TITLE
Tavern and hall overlapping

### PR DESCRIPTION
**Pull request by Fabrice-TIERCELIN**
Hi @misiokles,

This PR fixes the display of one house at the right of the tavern. It also updates one screenshot.

PS: Do you manage to take a screenshot? And how?

### CODE REVIEW

**Comment by misiokles** [comment]
Yeah, I press printscreeb button twice.

**Comment by Fabrice-TIERCELIN** [comment]
@misiokles, has the author (Fiorin) been notified of thoses fixes? Fiorin is preparing new content:
http://heroescommunity.com/viewthread.php3?TID=44951

**Comment by misiokles** [comment]
Fiorin is programmer, so I assume he tracks all changes at GitHub. But I guess, new public Ruins version will have completelly reworked townscreen.

**Comment by Fabrice-TIERCELIN** [comment]
Hi @Fiorin, I'm animating the water in Blender:

Lake
Have you planned to rework the townscreen?

**Comment by fiorin** [comment]
Hello @Fabrice-TIERCELIN, I missed the GH notifications about this one. The emails go to specific folder, so I didn´t checked.

As @misiokles have mentioned, the townscreen will be fully reworked for the new version. If you want to keep this one as a own version, no worries. In fact, I can check if I have the .blend file if that helps.

The new townscreen was not showed yet, but I can share the alpha background version:
Screenshot from 2023-09-07 14-09-36

**Comment by Fabrice-TIERCELIN** [comment]
@Fiorin. I won't create my own version. I think I will quickly finish the render to integrate it in the current version for the few time the current version will last. No matter if it's not featured in the further version, it can be reused in other towns.

I have started the translation into French. Why is it called "Ruins"? I see no ruins. Do you mean "Runes"? It sounds better, or "Druid".

If the sorceress is not used anymore, perhaps we should recycle it for another town, like Refugee.

**Comment by fiorin** [comment]
@Fabrice-TIERCELIN Sure. Be welcome. I will take a little bit longer still to release. There a few animations and the horses models pending... besides the towscreen. So, there is time yet.

The idea is something ancient, but the time I did the town I was struggling with the building models... so that was the outcome. The newest version will be more interesting I suppose 

I do not consider the sorceress model a good one, but after releasing the stable version I will be working on other neutral models or something else

**Comment by Fabrice-TIERCELIN** [comment]
@fiorin, can you give me the `.def` and images of [the original priestesses](https://www.youtube.com/watch?v=Z5FGbaCtHvo&t=146s), in both level? You would like to reuse it for the fairy town. The animations of Fairy town are low and it would fit.

**Pull request merged**
