### PR TITLE
Animate water

### PR DESCRIPTION
**Pull request by Fabrice-TIERCELIN**
Hi @misiokles,

This PR is a quick and dirty animation of the water. It also increments the version because it won't last a long time.

### CODE REVIEW

**Comment by Fabrice-TIERCELIN** [comment]
OK, @Fiorin, you can release the new version whenever you want. Another option would be to first change the portraits of the heroes, then change the render of the creatures and eventually change the townscreen. As you like.

**Comment by Fabrice-TIERCELIN** [comment]
@fiorin, should I rather translate the mod into French now or should I wait for the rework?

**Comment by fiorin** [comment]
@Fabrice-TIERCELIN I could release in steps, but I dont want to mix the current with the newest version.
All the heroes were reworked and their json code is working fine already. I have plans for their release, as the same for the creatures.
The towscreen will be released as an alpha version. I will rework each building after the release. I have decided for lower quality/already made models to avoid delaying too much right now. So, their models will not be the ones I really want. But they work. Then after I will changing slowly.
Right now I dont have all the creature animation ready. Still pending as well the heroes battle/adv models.
The map dwellings and the puzzle.

You can release the translation, but I will change  the buildings name on the town. That will break the germany and chinese translation we already have I know.

**Comment by Fabrice-TIERCELIN** [comment]
@fiorin, I give you some feedbacks about the new content. First of all, I only focus on the negative points, so don't worry.

1. The Walking Stones and the Colossus are breathing a lot. I wanna say a idle animation should move the less possible. Just enough so that the player can say "OK, it's not an image" or "It's not a basic animation like an image rotation". Less is more.
2. The Grand Peryton seems to have lots of metallic or specular. It reflects. Is that what you want?
3. The cloth of the Huntmaster looks fake. The motion should continue when the motion of the creature stops.
4. I don't know for the new animations but the original ones seemed to be animated manually. Do you know [BVH](https://docs.blender.org/manual/en/dev/addons/import_export/anim_bvh.html)? It's mostly useful for humanoid creatures.
5. You show me the new townscreen. Do you know [Stable Diffusion](https://stablediffusionweb.com/#demo)? You can have any background.

**Comment by fiorin** [comment]
@Fabrice-TIERCELIN Thanks for your input. They are welcome. Maybe we can talk outside this thread. Discord? Homm community?

**Comment by Fabrice-TIERCELIN** [comment]
@fiorin, I have created [a room on Gitter](https://app.gitter.im/#/room/#ruins-town:gitter.im)

**Comment by Fabrice-TIERCELIN** [comment]
I put here both the source and the result for anyone:
background

[ruins.blend](https://github.com/vcmi-mods/ruins-town/files/12616450/ruins.blend.txt) (remove the `.txt` extension and relink the background image on your computer)


Result:
Lake

**Comment by fiorin** [comment]
I can share the def and the images for priestesses for sure. Gitter? I have never used. Find me on the vcmi or era discord. nick fiorin there

**Comment by Fabrice-TIERCELIN** [comment]
Have you retrieved the priestesses, @fiorin?

**Comment by fiorin** [comment]
@Fabrice-TIERCELIN In fact, I have re-rendered the Priestess with the new setup and added as an alternate to the lineup:

Priestess

You can check the current updated line on the topic: http://heroescommunity.com/viewthread.php3?TID=44951

We are in a stable version, so now I will be balancing stats, polishing graphs and focusing on the pendings.

**Comment by Fabrice-TIERCELIN** [comment]
Hi @fiorin,

I wanted to say those priestesses:

https://www.youtube.com/watch?v=Z5FGbaCtHvo#t=2m26

It's for the Fairy town.

**Comment by fiorin** [comment]
Oh, I don't have that one anymore. I lost a few GB a few years ago on a bad HD. It must be there. Sorry

**Comment by Fabrice-TIERCELIN** [comment]
@misiokles, have you got his on your hard disk?

@fiorin, can you put a message to the players on your topic? Perhaps a player has still this town.

**Comment by misiokles** [comment]
@Fabrice-TIERCELIN I guess you're talking about this: https://www.mediafire.com/file/mjotz72vogzg6iu/Fastness.7z/file

**Comment by Fabrice-TIERCELIN** [comment]
That's it! @fiorin, you can retrieve your work 🙂Perhaps it represents nothing for you because it's the past but for the other modders, it's gold. It's full of smooth animations that can be recycled.

**Pull request merged**
